### ISSUE TITLE
Multiple quick clicks, empty sheet

### ISSUE THREAD

**Issue by fatcarter** [AndreaMiotto/PartialSheet#139]
When the button is in the same position as the cover, an empty sheet may appear if you click it a few times quickly

Like the picture below：
![image](https://user-images.githubusercontent.com/96217218/150294299-3d43715d-73a0-45d7-9208-fdee276be5ee.png)

How to fix it?

**Comment by Michael4zhang** [comment]
![9F309718-9219-4864-A346-7B31F1955568](https://user-images.githubusercontent.com/96217218/150560127-7201de3c-779f-4f64-b629-85d9e9c2c8ee.png)

**Comment by eenlars** [comment]
Same issue here. Still can't see a way to fix it. Maybe it would be good to include your code in here as well, so people might suggest a way to fix it

**Comment by PocketDaniel** [comment]
Had similar issue when I was closing partial sheet right before opening a new one, which resulted in an empty view due to `isPresented -> didSet` implementation, as it is clearing content to `AnyView(EmptyView())` after 0.35 seconds (I believe) delay (for details please refer to PartialSheetManager lines 27-36)

So, you might be calling `isPresented = false` while quick tapping as you either tap outside the sheet or your taps are recognised as "dismiss gesture".

**Comment by AndreaMiotto** [comment]
Check it out version 3. And the PSButton.
Rage tap can be avoided putting a delay on your button.

**Comment by baraql** [comment]
For people experiencing this issue and who want to use version 1 which is compatible with previous iOS versions:

I'm pretty sure this can be solved by simply checking if the sheet is still not presented. Here's my fix (lines 27-39 of PartialSheetManager.swift):

`@Published var isPresented: Bool = false
    {
        didSet {
            if !isPresented {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) { [weak self] in
                    if !(self?.isPresented ?? true) {
                        self?.content = AnyView(EmptyView())
                        self?.onDismiss = nil
                    }
                }
            }
        }
    }`
