### ISSUE TITLE
How to update content dynamically within sheet

### ISSUE THREAD

**Issue by triki97** [AndreaMiotto/PartialSheet#77]
Hey all, Ive been trying to update the content within the sheet while it is still loaded. Is there an easy way to do this besides closing and reopening the sheet every time?

**Comment by zirkler** [comment]
@triki97 would you mind sharing how you achieved it? Thanks.

**Comment by acarrera94** [comment]
if anyone runs into this it's because the colure is only called once the the sheet is shown. it doesn't listen for changes in the view that called it or the variables passed in. The solution is to use binding and pass in that binding to the sheet or pass in an environmentObject holding the dynamic data. Then the view will update with any changes to the environmentObject.
