### ISSUE TITLE
Doesn't build on an M1

### ISSUE THREAD

**Issue by codeslubber** [AndreaMiotto/PartialSheet#86]
What a joke.

![image](https://user-images.githubusercontent.com/603642/109361407-be8a3980-783d-11eb-8973-c22659a61bc7.png)

Here's the error as text:

Could not find module 'PartialSheet' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

What a waste of time.

**Comment by AustinFuller** [comment]
Not certain what your problem is, but it isn't this repo. I downloaded and ran on my M1 Mac without issue. 

Also, check yourself. Open source repository owners are offering you something for free. 

If you had a better tone, I'm sure people would be more interested in helping you figure out what the problem is.

**Comment by codeslubber** [comment]
Another case closed with the 'works for me.'

In fact, I did make a new project and added this repo and it worked. But the documentation is so poor on Package Manager that I couldn't figure out why SPM didn't just make the x86_64 variant, which would have made this work. The problem (at least my theory) is that Amazon does not compile to M1 yet so Xcode is smart enough that if it knows it cannot get a build for the simulator that is arm64, it attempts to run the app using Rosetta. But because SPM is not building that it doesn't work. The Carthage built dependencies also run in sim when there are no SPM deps.

As to me 'checking myself,' ok check is done. Sorry I said what a waste of time. Wow that really is amazing I should be shunned for that.
